excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kaushik-ghosh.github.io
title: Kaushik Ghosh
email: 
author: kaushik-ghosh
description: My awesome new site
paginate: 3
google_analytics: 